#!/usr/bin/env bash
# Report kona-required kernel options present in a kernel .config.
# usage: check-config.sh <config>   (e.g. kernel/base-arm64.config)
set -euo pipefail
cfg=${1:?config file}
opts=(
  CGROUPS MEMCG CGROUP_PIDS CPUSETS CFS_BANDWIDTH CGROUP_BPF
  NAMESPACES NET_NS USER_NS SECCOMP
  OVERLAY_FS VETH BRIDGE BRIDGE_NETFILTER TUN DUMMY
  NETFILTER NF_CONNTRACK NF_NAT NF_TABLES NFT_COMPAT NFT_CT NFT_NAT NFT_MASQ
  IP_NF_IPTABLES IP_NF_FILTER IP_NF_NAT IP_NF_TARGET_MASQUERADE IP_NF_MANGLE IP_NF_RAW
  IP6_NF_IPTABLES IP6_NF_NAT
  NETFILTER_XT_MATCH_COMMENT NETFILTER_XT_MATCH_CONNTRACK NETFILTER_XT_MATCH_MULTIPORT
  NETFILTER_XT_MATCH_STATISTIC NETFILTER_XT_MARK NETFILTER_XT_TARGET_TPROXY NETFILTER_XT_SET
  IP_SET IP_SET_HASH_IP IP_SET_HASH_NET
  IP_VS IP_VS_RR IP_VS_WRR IP_VS_SH IP_VS_NFCT IP_VS_PROTO_TCP IP_VS_PROTO_UDP
  BPF_SYSCALL BPF_JIT BPF_JIT_ALWAYS_ON BPF_EVENTS DEBUG_INFO_BTF
  NET_CLS_BPF NET_CLS_ACT NET_SCH_INGRESS NET_ACT_BPF NET_SCH_FQ
  VXLAN GENEVE WIREGUARD XFRM CRYPTO_USER_API_HASH CRYPTO_SHA1
  PERF_EVENTS SCHEDSTATS NETKIT
  NETFILTER_XT_TARGET_CT NETFILTER_XT_MATCH_MARK NETFILTER_XT_MATCH_SOCKET
  NF_SOCKET_IPV4 NF_SOCKET_IPV6
  DRM DRM_VIRTIO_GPU
  IKCONFIG_PROC MODULES
)
for o in "${opts[@]}"; do
  line=$(grep -E "^(# )?CONFIG_${o}[= ]" "$cfg" || true)
  case "$line" in
    "CONFIG_${o}=y") s=y ;;
    "CONFIG_${o}=m") s=m ;;
    "") s=absent ;;
    *) s=no ;;
  esac
  printf '%-32s %s\n' "$o" "$s"
done
