#!/usr/bin/env bash
# Capture the CLI surface of the host tools kona drives, verbatim, so flag
# usage in code can be checked against observed behavior.
# usage: hack/capture-cli.sh > docs/cli-surface.md
set -uo pipefail

VMNET_HELPER=$(brew --prefix vmnet-helper 2>/dev/null)/libexec/vmnet-helper

section() {
  printf '\n### `%s`\n\n```text\n' "$*"
  "$@" 2>&1
  printf '```\n'
}

echo "# Host tool CLI surface"
echo
echo "Generated by \`hack/capture-cli.sh\` on $(date -u +%Y-%m-%d) ($(sw_vers -productVersion), $(uname -m))."

section sw_vers
section container --version
section container --help
section container system --help
section container system kernel set --help
section container run --help
section container network create --help
section container volume create --help
section container machine create --help
section container k8s create --help
section krunkit --version
section krunkit --help
section "$VMNET_HELPER" --version
section "$VMNET_HELPER" --help
